#!/bin/bash
# MoAI Agent Hook Wrapper - Generated by moai-adk
# This script handles agent-specific hook events.
# Usage: handle-agent-hook.sh <action>
# Example: handle-agent-hook.sh ddd-pre-transformation
#
# Agent Hook Actions:
# Manager Agents:
#   - ddd-pre-transformation, ddd-post-transformation, ddd-completion
#   - tdd-pre-implementation, tdd-post-implementation, tdd-completion
#   - spec-completion, quality-completion, docs-verification, docs-completion
# Expert Agents:
#   - backend-validation, backend-verification
#   - frontend-validation, frontend-verification
#   - testing-verification, testing-completion
#   - debug-verification, debug-completion
#   - devops-verification, devops-completion

set -e

# Get action from first argument (use lowercase to avoid template token detection)
action="$${1:-}"
if [ -z "$action" ]; then
    echo "Error: No action specified" >&2
    echo "Usage: $$0 <action>" >&2
    exit 1
fi

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
    exec moai hook agent "$action" < "$temp_file"
fi

# Try detected Go bin path from initialization
if [ -f "/Users/taemyungheo/go/bin/moai" ]; then
    exec "/Users/taemyungheo/go/bin/moai" hook agent "$action" < "$temp_file"
fi

# Try default ~/go/bin/moai
if [ -f "/Users/taemyungheo/go/bin/moai" ]; then
    exec "/Users/taemyungheo/go/bin/moai" hook agent "$action" < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
