#!/bin/bash
# MoAI WorktreeCreate Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook worktree-create command.
# Project-local hook: .claude/hooks/moai/handle-worktree-create.sh

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook worktree-create < "$temp_file"
fi

# Try detected Go bin path from initialization
if [ -f "/Users/taemyungheo/go/bin/moai" ]; then
	exec "/Users/taemyungheo/go/bin/moai" hook worktree-create < "$temp_file"
fi

# Try default ~/go/bin/moai
if [ -f "/Users/taemyungheo/go/bin/moai" ]; then
	exec "/Users/taemyungheo/go/bin/moai" hook worktree-create < "$temp_file"
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
